### PR TITLE
Add filtering by ideal date to the scheduled activity report.

### PR DESCRIPTION
**Pull request by hannahwhy**
Let me know if you'd prefer this to be teased apart into separate test and implementation commits.

### CODE REVIEW

**Comment by rsutphin** [comment]
I see [unit test failures](https://gist.github.com/192f8952ef840baf3e60) when I apply this to trunk.

Any ideas?

**Comment by hannahwhy** [comment]
None yet; I didn't see those when I ran `ScheduledActivityReportJsonRepresentationTest` nor `ScheduledActivityReportResourceTest` via IDEA's unit test runner.

I'll take a look at those tomorrow.

**Comment by hannahwhy** [comment]
The unit test failures you pointed out should now be fixed.  I've also updated `ScheduledActivityReportResourceTest` so that it includes test cases for the ideal date filters.

**Comment by rsutphin** [comment]
Squashed into a single commit and merged into PSC svn as r7066. Should show up in the mirror within 30 minutes.

For future reference, this was [PSC issue 1762](https://code.bioinformatics.northwestern.edu/issues/issues/show/1762).

**Pull request closed without merging**
